projVersion=1.0

wildfly.home=/home/maxkarn/Desktop/wildfly/wildfly-39.0.1.Final

env.java.executable=java
env.jvm.args=-Dwildfly.home=/home/maxkarn/Desktop/wildfly/wildfly-39.0.1.Final \
             -Dwildfly.admin.name=admin \
             -Dwildfly.admin.password=admin \
             -Dwildfly.jdbc.driver=/home/maxkarn/Desktop/labs/opi/lab3/web_lab3/psql_jdbc_driver/postgresql-42.7.8.jar\
             -Dwildfly.wait=45

